[project]
name = "tabcal"
version = "0.0.1"
description = "predicting calendar blocks with tabpfn 3.5"
requires-python = ">=3.11"
dependencies = [
    "tabpfn-client",
    "pandas",
    "tabpfn",
    "torch",
    "typer",
    "scikit-learn",
    "scipy",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "RUF012",  # mutable-class-default
]
